#!/usr/bin/env bash

if [[ -d src/ ]]; then
	echo "building src/"
	cd src/
else
	echo "building locally"
fi

options="-Xlint"
javac $options *.java

options="-f OpenChat.jar -c"
jar $options *.java
chmod +x OpenChat.jar
